apiVersion: v2
name: pika
description: A Pika cluster definition Helm chart for Kubernetes

type: application

version: 0.6.0-alpha.21

appVersion: "3.5.0"

home: https://github.com/OpenAtomFoundation/pika
keywords:
  - pika
  - redis
  - database
  - nosql
  - replication
  - codis

maintainers:
  - name: pika
    url: https://github.com/OpenAtomFoundation/pika/tools/helm
