pika:
  version: v3.5.2
image:
  pika:
    registry: docker.io
    repository: pikadb/pika
    tag: 3.5.2.0
    pullPolicy: IfNotPresent
  codis:
    registry: docker.io
    repository: pikadb/codis
    tag: 3.5.2.0
    pullPolicy: IfNotPresent
  etcd:
    registry: docker.io
    repository: bitnami/etcd
    tag: 3.5.9
    pullPolicy: IfNotPresent

roleProbe:
  pika:
    failureThreshold: 2
    periodSeconds: 1
    timeoutSeconds: 1
  codis-proxy:
    failureThreshold: 2
    periodSeconds: 1
    timeoutSeconds: 1
  codis-dashboard:
    failureThreshold: 2
    periodSeconds: 1
    timeoutSeconds: 1
  codis-fe:
    failureThreshold: 2
    periodSeconds: 1
    timeoutSeconds: 1
  etcd:
    failureThreshold: 2
    periodSeconds: 1
    timeoutSeconds: 1

clusterVersionOverride: 3.5.2
nameOverride: ""
fullnameOverride: ""

clusterDomain: ".cluster.local"
